apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-container-app
  template:
    metadata:
      labels:
        app: multi-container-app
    spec:
      containers:
        - name: container-1
          image: alpine
          args:
            - /bin/sh
            - -c
            - >
              i=1;
              while true;
              do
                echo "$i: $(date)" >> /mount/log$i.log;
                i=$((i+1));
                sleep 60;
              done
          volumeMounts:
            - name: shared-volume
              mountPath: /mount
        - name: container-2
          image: alpine
          args:
            - /bin/sh
            - -c
            - >
              i=1;
              while true;
              do
                echo "$i: $(date)" >> /mount/file$i.log;
                i=$((i+1));
                sleep 60;
              done
          volumeMounts:
            - name: shared-volume
              mountPath: /mount
      volumes:
        - name: shared-volume
          emptyDir: {}
